name: deploy on gh pages
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: pwd && ls -la

      - name: Install dependencies
        run: npm i


      - name: Build application
        run: npm run build
        env:
          VUE_APP_BASE_API: ${{ secrets.VUE_APP_BASE_API }}
          VUE_APP_USER_CONSOLE_URL: ${{ secrets.VUE_APP_USER_CONSOLE_URL }}
          VUE_APP_INSTANCE_DB_NAME_PREFIX: ${{ secrets.VUE_APP_INSTANCE_DB_NAME_PREFIX }}
          VUE_APP_INSTANCE_DB_HOST: ${{ secrets.VUE_APP_INSTANCE_DB_HOST }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
